dist: trusty
sudo: false
language: php
php:
- 7.1
node:
- 4
matrix:
  fast_finish: true
addons:
  hosts:
  - localhost
cache:
  directories:
  - "${HOME}/.composer/cache"
  - "${HOME}/vendor-cache/"
  - "$HOME/.yarn-cache"
git:
  depth: 3
before_install: "${TRAVIS_BUILD_DIR}/build/travis/before_install.sh"
install: "${TRAVIS_BUILD_DIR}/build/travis/install.sh"
script: "${TRAVIS_BUILD_DIR}/build/travis/script.sh"
before_cache: "${TRAVIS_BUILD_DIR}/build/travis/before_cache.sh"
notifications:
  slack:
    secure: IQfjz0aXkk0WtsFofO+ShVwjpjVNAZYeAm5Pll/99qgHQcvu7uf8GgVo9xYRq4VBf6lC+JYYdoxvY3WPg/R0NzA5lxeXmr9I/UgpQPWiuGc6WCJup96XKAbwJvHD1oSTzoJx60HhTMdLKzw0frSfThuc8SpK5r7XRhRz6bFAXmn1aT06YgI+HhSGNHWjpLF0TOK/ru5maSlXzwHJnMdEwOVxqDHmK2XOxhJk3vTDH9bsUIo/wHQQFHu5FtcPX8utRUoe2DNEWn6t3JbuHBLE2Hw0GgQRxdMOprYW6jp6osaz3cKhvHW1nxU1S3HKPCwBvKAijLnKUWB3+TRKFcxVHygENegSSulTbB8FDfNWjWdIzbGZYvtyTum1QoGfCCivM2BdtydkDVdkVshdW659/uDFnCFUO+zdsBHQ+54UGY/tkIQagy0n6CX4hcbG5FMfWeu4FRVhyumWRZi+ohw0p2FPUD0UFryW77wwgrwx4xM56Irw79IPc6NdFxF3ggsqSdiP4fC9v+RVZ2iM1r+coOY3pKH9A1SU85MkVcMSw+97RammUGTW/ei7w/8S4OOOe7I/RchJinikfcUJPL+HxzLUQG+yy1bxpeM/u4/TdsL1Nh4vJM1zHEUeiqAX7NndAF+TyhDA+/0bqXMd0gl/VL3Ivh6PHfYkaEJBe92XQ8A=
