# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: d8starter.dev
vagrant_machine_name: d8starter
vagrant_ip: 0.0.0.0

# Set 'build_makefile' to 'false' and this to 'true' if you are using a
# composer based site deployment strategy.
drupal_build_composer: true
drupal_composer_path: "{{ config_dir }}/composer.json"
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_composer_dependencies: []

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
drupal_build_composer_project: false
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction -o"

# Settings for installing a Drupal site if 'drupal_install_site:' is 'true'.
drupal_install_site: false
drupal_major_version: 8
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal 8 Starter"
drupal_install_profile: config_installer
drupal_enable_modules: []

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs:
  - {
    name: "Drupal Cron",
    minute: "*/30",
    job: "drush -r {{ drupal_core_path }} core-cron"
  }

# Databases.
drupal6_db_user: drupal6
drupal6_db_password: drupal6
drupal6_db_name: drupal6
drupal7_db_user: drupal7
drupal7_db_password: drupal7
drupal7_db_name: drupal7

# MySQL databases and users.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8
    collation: utf8_general_ci
#  - name: "{{ drupal6_db_name }}"
#    encoding: utf8
#    collation: utf8_general_ci
#  - name: "{{ drupal7_db_name }}"
#    encoding: utf8
#    collation: utf8_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"
#  - name: "{{ drupal6_db_user }}"
#    host: "%"
#    password: "{{ drupal6_db_password }}"
#    priv: "{{ drupal6_db_name }}.*:ALL"
#  - name: "{{ drupal7_db_user }}"
#    host: "%"
#    password: "{{ drupal7_db_password }}"
#    priv: "{{ drupal7_db_name }}.*:ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  # - varnish
  - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+

# PHP Configuration. Currently-supported versions: 5.6, 7.0.
# To use 5.6, see: http://docs.drupalvm.com/en/latest/other/php-56/
php_date.timezone: "America/Chicago"
php_upload_max_filesize: "50M"
php_post_max_size: "50M"
php_output_buffering: "Off"
drush_version: "8.1.15"

post_provision_scripts:
  - "{{ config_dir }}/scripts/drupalvm/post-provision.sh"

# MySQL Configuration.
mysql_max_allowed_packet: 512M

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x", "6.x".
nodejs_npm_global_packages:
  - name: yarn

# Other configuration.
ssh_home: "{{ drupal_core_path }}"
